# Generated by Django 5.0.6 on 2024-07-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('categoria_producto', models.IntegerField(verbose_name='Categoría del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id_procesador', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del procesador')),
                ('nombre_procesador', models.CharField(max_length=50, verbose_name='Nombre del procesador')),
                ('valor_procesador', models.PositiveIntegerField(verbose_name='Valor del procesador')),
                ('descripcion_procesador', models.CharField(max_length=500, verbose_name='Descripción del procesador')),
                ('imagen_procesador', models.CharField(max_length=250, verbose_name='Imagen del procesador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesadores', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id_gabinete', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del gabinete')),
                ('nombre_gabinete', models.CharField(max_length=50, verbose_name='Nombre del gabinete')),
                ('valor_gabinete', models.PositiveIntegerField(verbose_name='Valor del gabinete')),
                ('descripcion_gabinete', models.CharField(max_length=500, verbose_name='Descripción del gabinete')),
                ('imagen_gabinete', models.CharField(max_length=250, verbose_name='Imagen del gabinete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gabinetes', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id_disco_duro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del disco duro')),
                ('nombre_disco', models.CharField(max_length=50, verbose_name='Nombre del disco')),
                ('valor_disco', models.PositiveIntegerField(verbose_name='Valor del disco')),
                ('descripcion_disco', models.CharField(max_length=300, verbose_name='Descripción del disco')),
                ('imagen_disco', models.CharField(max_length=250, verbose_name='Imagen del disco')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos_duros', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaVideo',
            fields=[
                ('id_tarjeta_video', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la tarjeta de video')),
                ('nombre_tarjeta_video', models.CharField(max_length=50, verbose_name='Nombre de la tarjeta de video')),
                ('valor_tarjeta_video', models.PositiveIntegerField(verbose_name='Valor de la tarjeta de video')),
                ('descripcion_tarjeta_video', models.CharField(max_length=500, verbose_name='Descripción de la tarjeta de video')),
                ('imagen_tarjeta_video', models.CharField(max_length=250, verbose_name='Imagen de la tarjeta de video')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_video', to='core.producto')),
            ],
        ),
    ]
