# Generated by Django 5.0.6 on 2024-07-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolHardware',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id rol')),
                ('nombreRol', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioHardware',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombreUsuario', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('numero_telefonico', models.CharField(default='0000000000', max_length=20, verbose_name='Número Telefónico (+56)')),
                ('correo', models.EmailField(max_length=40)),
                ('contraseña', models.CharField(max_length=128)),
                ('fechacreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rolhardware')),
            ],
        ),
    ]
