# Generated by Django 5.0.6 on 2024-07-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolhardware_usuariohardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabinete',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='tarjetavideo',
            name='producto',
        ),
        migrations.DeleteModel(
            name='DiscoDuro',
        ),
        migrations.DeleteModel(
            name='Gabinete',
        ),
        migrations.DeleteModel(
            name='Procesador',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TarjetaVideo',
        ),
    ]
