# Generated by Django 5.0.6 on 2024-07-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuariohardware_custom_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariohardware',
            name='custom_user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
