# Generated by Django 5.0.6 on 2024-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_discoduro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoduro',
            name='imagen_disco',
            field=models.ImageField(max_length=250, upload_to='', verbose_name='Imagen del disco'),
        ),
    ]
