# Generated by Django 5.0.6 on 2024-07-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_discoduro_producto_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoduro',
            name='imagen_disco',
            field=models.ImageField(null=True, upload_to='pcbuilds'),
        ),
    ]
