# Generated by Django 5.0.6 on 2024-07-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_discoduro_imagen_disco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoduro',
            name='imagen_disco',
            field=models.ImageField(default='discosduros/default.jpg', upload_to='discosduros/'),
        ),
    ]
