# Generated by Django 5.0.6 on 2024-07-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_discoduro_imagen_disco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id_gabinete', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del gabinete')),
                ('nombre_gabinete', models.CharField(max_length=50, verbose_name='Nombre del gabinete')),
                ('valor_gabinete', models.PositiveIntegerField(verbose_name='Valor del gabinete')),
                ('descripcion_gabinete', models.CharField(max_length=300, verbose_name='Descripción del gabinete')),
                ('imagen_gabinete', models.ImageField(default='gabinetes/default.jpg', upload_to='gabinetes/')),
            ],
        ),
    ]
