# Generated by Django 5.0.6 on 2024-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gabinete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id_procesador', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del procesador')),
                ('nombre_procesador', models.CharField(max_length=50, verbose_name='Nombre del procesador')),
                ('valor_procesador', models.PositiveIntegerField(verbose_name='Valor del procesador')),
                ('descripcion_procesador', models.CharField(max_length=300, verbose_name='Descripción del procesador')),
                ('imagen_procesador', models.ImageField(default='procesadores/default.jpg', upload_to='procesadores/')),
            ],
        ),
    ]
